apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: example-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - cat
                - some_data.txt
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: container-data
              mountPath: /some_data.txt
              subPath: some_data.txt
      volumes:
        - name: container-data
          configMap:
            name: config

