apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grzegorz-example-apps
  namespace: argocd
spec:
  project: grzegorz
  source:
    repoURL: https://github.com/grzegorz-demidziuk/exampleChart.git
    targetRevision: main
    path: "./example-chart"
    helm:
      values: |-
        config:
          text: |
            Tekst ten jest zdefiniowany w pliku application.yaml.
  destination:
    server: "https://kubernetes.default.svc"
    namespace: playground
  syncPolicy: 
    automated: {}
 